name: Close stale issues

on:
  schedule:
    - cron: "0 2 * * *" # runs daily
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          days-before-stale: 7
          days-before-close: 14

          stale-issue-label: stale

          stale-issue-message: |
            ‚ö†Ô∏è This issue has been inactive for 7 days.

            If no further activity occurs, it will be automatically closed in 7 more days.

            Please comment if this issue is still relevant.

          close-issue-message: |
            üîí This issue has been closed due to inactivity.

            Feel free to reopen it if the problem persists or new information is available.

          exempt-issue-labels: |
            priority: high
            keep-open
